name: Update Articles

on:
  schedule:
    - cron: '0 */6 * * *'  # كل 6 ساعات
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Generate new articles
        run: node server/scripts/generateArticles.js

      - name: Commit articles.json changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add server/data/articles.json
          git commit -m "Auto-update articles [github action]" || echo "No changes"
          git push
